### ISSUE TITLE
AD7124 default device?

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#10]
With nothing attached to my Pi, I get:

```
root@analog:/usr/local/src/linux_image_ADI-scripts# iio_attr -d
IIO context has 2 devices:
	iio:device0: ad7124-4, found 0 device attributes
	trigger0: ad7124-4-dev0, found 0 device attributes
root@analog:/usr/local/src/linux_image_ADI-scripts# iio_attr -c
IIO context has 2 devices:
	iio:device0: ad7124-4, found 8 channels
	trigger0: ad7124-4-dev0, found 0 channels
```

```
 dmesg | grep -i ad7
[   10.290929] ad7124 spi0.0: Linked as a consumer to regulator.2
```

Why does it think there is a ad7124-4 attached?

https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/adc/ad7124.c#L690
should fail? Shouldn't it?

Register`AD7124_ID` should be a `04` or a `06`. I don't see that read in the probe function, and exiting if it is not there...

?

**Comment by mirceacaprioru** [comment]
That drivers is checked because it is set in the config.txt. The new image version will not have anything enabled by default. 

Also that driver does not check for Register AD7124_ID so it will not fail if nothing is attached. This is just something that was not added to this driver. 

This should be addressed on the Linux repository.

**Comment by rgetz** [comment]
OK - I opened https://github.com/analogdevicesinc/linux/issues/987

When is the next RC schedule for this image?

**Comment by mirceacaprioru** [comment]
I would like to have it up by Friday so it is my main focus this week. Any feedback/suggestions on improving things and fixing bugs are welcomed.

**Comment by rgetz** [comment]
Ok - closing this. Thanks
