### ISSUE TITLE
does not include /etc/init.d/iiod

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#11]
The lines in `adi_update_tools.sh` look in `/sys/firmware/devicetree/base/model` for ADI or Zynq, and then fall back to:

```
if [ -f iiod/init/iiod.init ] ; then
```

will not work, since that file will only be there after CMAKE, since it needs to be processed by the cmake.

It's better to check on what system you are running, and then pass the right flag to the libiio cmake, so it builds it.`WITH_SYSTEMD` or `WITH_SYSVINIT` or` WITH_UPSTART`

**Comment by mirceacaprioru** [comment]
Will look into it to add it to adi_update_tools script

**Comment by mirceacaprioru** [comment]
Added modification in https://github.com/analogdevicesinc/linux_image_ADI-scripts/pull/18

**Comment by rgetz** [comment]
Thanks - will close this, and follow up there...
