### ISSUE TITLE
libiio Python bindings not found when running as root

### ISSUE THREAD

**Issue by mthoren-adi** [analogdevicesinc/adi-kuiper-gen#15]
This might be a non-issue, but it came up when running a setup script that sets the sample rate of the AD7124 ADC. When running as user analog, you can't set iio attributes via the local context (which is normal, I think.) Running the script as root (sudo) should have worked, but fails when trying to import iio. appending /lib/python3.7/site-packages to path then works.

@tfcollins had suggested adding user analog to a group that had write access to iio attributes, maybe that's the best solution.

(Switching the script to use the network context (ip:localhost) such that everything is done through iiod was a workaround, but it would be better to not have to do that.)

**Comment by tfcollins** [comment]
You have to update the udev rules or being part of the wheels group should do it
