### ISSUE TITLE
turn off screen blanking 

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#16]
I needed to add:

```
@xset s off
@xset -dpms
```

to the `/etc/xdg/lxsession/LXDE-pi/autostart` file to get screen blanking to turn off (which is needed during tradeshows/etc.

I also needed to do a `sudo apt install xscreensaver` to make sure things were working (which has a preferences in the GUI, and is trivial to turn on/off).

**Comment by mirceacaprioru** [comment]
solved with https://github.com/analogdevicesinc/adi-kuiper-gen/pull/21

**Comment by rgetz** [comment]
Thanks

**Comment by rgetz** [comment]
confirm on 2019R2-RC5 - no blanking, no screen saver.

Thanks

**Comment by rgetz** [comment]
should the `xscreensaver` be installed be default?
