### ISSUE TITLE
Unencrypted VNC connection

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/adi-kuiper-gen#19]
After I write the image on the SD card and create an empty text file named "vnc" on the root directory when I try to connect on the PI through VNC I receive the following:

![image](https://user-images.githubusercontent.com/13637543/83515153-90114500-a4dd-11ea-9e35-7d15ed32a629.png)

![image](https://user-images.githubusercontent.com/13637543/83515243-b9ca6c00-a4dd-11ea-8a13-8bf69483bc0e.png)

The issue was found on this image_2020-05-06-ADI-Kuiper-full.

**Comment by rgetz** [comment]
Which VNC is being used? I don't think we can distribute the default Raspberrian one, as it requires a commercial license. (I thought).

**Comment by mirceacaprioru** [comment]
we are using x11vnc it is open source, so we removed the realvnc default one just to remove that commercial license. Will investigate to see how to encrypt the connection.

**Comment by msuciu** [comment]
Not so sure about that since the VNC option is not enabled into raspi-config.

![image](https://user-images.githubusercontent.com/13637543/83520068-be931e00-a4e5-11ea-9012-7cc28a1271fe.png) 

![image](https://user-images.githubusercontent.com/13637543/83520320-29dcf000-a4e6-11ea-9ff3-feffa35bc1f0.png)

**Comment by rgetz** [comment]
Ok - thanks I confrmed on mine:
```
analog@analog:~ $ which x11vnc
/usr/bin/x11vnc
```

I think we just need to start it with the `-ssl` flag?

**Comment by rgetz** [comment]
I think it gets started from either:

`/etc/systemd/system/x11vnc.service`
OR 
`/etc/systemd/system/multi-user.target.wants/x11vnc.service`

**Comment by mirceacaprioru** [comment]
will try the -ssl flag

**Comment by rgetz** [comment]
I'm pretty sure we do not want a cert generated every time (you would get a warning every time you attach), what we want is something that is created once, but is unique to each SD Card...
