### ISSUE TITLE
Appearances after upgrade

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/adi-kuiper-gen#20]
After running the following commands "sudo apt-get update", "sudo apt-get upgrade" and a reboot the appearances are changed. In this case, the start button disappears after the Raspberry Pi reboot itself.

![image](https://user-images.githubusercontent.com/13637543/83516127-34e05200-a4df-11ea-9dd9-8d00e0260aeb.png)

![image](https://user-images.githubusercontent.com/13637543/83516831-7ae9e580-a4e0-11ea-809d-54fa440d5df5.png)

After I run "sudo apt-get dist-upgrade" and a reboot I see the start button, but has another icon on it.

![image](https://user-images.githubusercontent.com/13637543/83517789-2a738780-a4e2-11ea-8b3d-9a857969ed5b.png)

The issue was found on this image_2020-05-06-ADI-Kuiper-full.

**Comment by mirceacaprioru** [comment]
solved with https://github.com/analogdevicesinc/adi-kuiper-gen/pull/21
