### ISSUE TITLE
Docker Containers

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/adi-kuiper-gen#22]
Generating some docker containers we can use for testing in other projects would be really handy.

**Comment by mirceacaprioru** [comment]
Docker containers running the Kuiper image?

**Comment by tfcollins** [comment]
Yeah should be possible. Looking for a way to add testing for Kuiper and docker (or qemu) would probably be the easiest.

-Travis

**Comment by SRaus** [comment]
Docker containers will be available for kuiper2.0.
