### ISSUE TITLE
Kuiper build is failing on Stage6

### ISSUE THREAD

**Issue by SRaus** [analogdevicesinc/adi-kuiper-gen#24]
Kuiper build is failing with next error on Stage6 , substage 04-gnu-radio-m2k:

_Entering directory '/qwtpolar/qwtpolar-1.1.1/src'
compiling qwt_polar_fitter.cpp
compiling qwt_polar_item.cpp
compiling qwt_polar_picker.cpp
compiling qwt_polar_panner.cpp
qwt_polar_fitter.cpp: In constructor 'QwtPolarFitter::QwtPolarFitter(int)':
qwt_polar_fitter.cpp:28:82: error: 'Polygon' is not a member of 'QwtCurveFitter'
 QwtPolarFitter::QwtPolarFitter( int stepCount ) : QwtCurveFitter(QwtCurveFitter::Polygon)
make[1]: *** [Makefile:554: obj/qwt_polar_fitter.o] Error 1_

As workaround I just don't build "qwt" and "qwtpolar", since I dont use them for now, by commenting lines 211 and 212 from https://github.com/analogdevicesinc/adi-kuiper-gen/blob/master/stage6/04-gnuradio-m2k/00-run.sh

**Comment by mirceacaprioru** [comment]
fixed with https://github.com/analogdevicesinc/adi-kuiper-gen/pull/30
