### ISSUE TITLE
Kuiper build fails randomly with 'fdisk' error

### ISSUE THREAD

**Issue by SRaus** [analogdevicesinc/adi-kuiper-gen#26]
Error message:

_Begin /pi-gen/export-image/prerun.sh 
Welcome to fdisk (util-linux 2.33.1).
Changes will remain in memory only, until you decide to write them. Be careful before using the write command.
Command (m for help): Partition number (1-3, default 3): Hex code (type L to list all codes): 
Changed type of partition 'Linux' to 'unknown'.
Command (m for help): The partition table has been altered. Syncing disks.
losetup: /pi-gen/work/2020-07-24-Raspbian/export-image/2020-07-24-Raspbian-lite.img: failed to set up loop device: No such file or directory_

I have tried to build Kuiper using build-docker.sh and above issue is reproduced randomly, with a repro rate of about 1 out of 10 runs.

**Comment by mirceacaprioru** [comment]
This is somewhat dependent on the system that the process is running. A workaround is just to trigger the image generation stage only when this happens. Also from https://github.com/analogdevicesinc/adi-kuiper-gen/pull/30 only the full image is generated thus limiting this issue to just one/build process so the issue occurrence should go down.
