### ISSUE TITLE
Kuiper lite version should not be built  

### ISSUE THREAD

**Issue by SRaus** [analogdevicesinc/adi-kuiper-gen#27]
When a Kuiper build is done, in output folder (./deploy) are a lot of files and folders: 3 archives, 3 folders and 3 *.info.
Since **_lite_** version is not used, it can be disabled from build process - making the build time and occupied space smaller.

**Comment by mirceacaprioru** [comment]
fixed with https://github.com/analogdevicesinc/adi-kuiper-gen/pull/30
