### ISSUE TITLE
Gnuradio qtgui missing

### ISSUE THREAD

**Issue by mthoren-adi** [analogdevicesinc/adi-kuiper-gen#33]
Testing image_2020-09-11-ADI-Kuiper-full.zip

Running any flowgraph that includes qt blocks fails:

ImportError: cannot import name 'qtgui' from 'gnuradio'

side note - had to run ldconfig before GNURadio would run, perhaps add that as a very last step in the process?

Edit: Same issue on image_2020-09-22-ADI-Kuiper-full_RC1

**Comment by mthoren-adi** [comment]
A quick note that might help zero in on this - tried building GR 3.8.3 on Kuiper RC8 to test out some old GR projects, following instructions step by step. From the output of cmake:

...
...
-- Python checking for PyQt5 - found
-- QWT Version: 6.4.0
-- QWT Version must be >= 5.2 and <= 6.2.0, Found 6.4.0
...
...
-- ######################################################
-- # Gnuradio disabled components                        
-- ######################################################
--   * gr-qtgui
--   * gr-uhd
...
...

This would seem to indicate that version 6.1 is being installed:
https://github.com/analogdevicesinc/adi-kuiper-gen/blob/2019_R2/stage6/04-gnuradio-m2k/00-run.sh#L11

But looking further down, it seems gnuradio is built first, then qwt. Could that make a difference? (Just a guess...)

**Comment by mirceacaprioru** [comment]
This one is also related to qwt-polar which for now uses a different branch thatn gnuradio in order to be compatible with Scopy.

**Comment by mthoren-adi** [comment]
Looks like this is fixed in the "28 July 2021 release candidate", but I did have to run ldconfig before it would run.
("no module named '_runtime_swig'")
I'd imagine this might affect other things? Could ldconfig be run as the image is being built?

**Comment by SRaus** [comment]
" ldconfig" command was added.
