### ISSUE TITLE
ADALM2000 not recognized as connected

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/adi-kuiper-gen#34]
When trying to run an libm2k script and the uri for ADALM2000 is not specified, the device is not recognized even if the M2k folder is visible in File Manager.

**Comment by rgetz** [comment]
does the same happen for just `iio_info -S`?

**Comment by andreeaipop** [comment]
when running` iio_info -s ` m2k is not listed in the Available contexts list (0: Local devices [local: ])

**Comment by commodo** [comment]
does it work with `sudo iio_info -s` ?

**Comment by andreeaipop** [comment]
no, it is the same message. The library version I use is 0.19

**Comment by rgetz** [comment]
I just tried on 2019R2-RC5

```
root@analog:~# tail -4 /proc/cpuinfo 
Hardware	: BCM2835
Revision	: c03111
Serial		: 100000007ebb81ad
Model		: Raspberry Pi 4 Model B Rev 1.1
root@analog:~# iio_info -s usb
Library version: 0.21 (git tag: 8b5a339)
Compiled with backends: local xml ip usb
Available contexts:
	0: (Local IIO devices on Raspberry Pi 4 Model B Rev 1.1) [local:]
	1: 0456:b672 (Analog Devices Inc. M2k (ADALM-2000)), serial=104473f6078f000612002300d3e68dc95f [usb:1.6.5]
	2: 192.168.2.10 ) [ip:analog-2.local]
	3: 2601:190:400:3037:6f1d:2327:a811:8844 ) [ip:analog-2.local]
	4: 2601:190:400:3037:250f:6b17:5aa3:fb72 (ad7291,ad9361-phy,xadc,adf4351-udc-tx-pmod,adf4351-udc-rx-pmod,cf-ad9361-dds-core-lpc,cf-ad9361-lpc) [ip:analog.local]
	5: 192.168.1.120 ) [ip:analog-2.local]
	6: 192.168.1.116 (ad7291,ad9361-phy,xadc,adf4351-udc-tx-pmod,adf4351-udc-rx-pmod,cf-ad9361-dds-core-lpc,cf-ad9361-lpc) [ip:analog.local]
```

the usb context shows up for me.

**Comment by commodo** [comment]
> no, it is the same message. The library version I use is 0.19

i'm wondering if this is related to  https://github.com/analogdevicesinc/adi-kuiper-gen/issues/43#issuecomment-732089677
0.19 is pretty old;

**Comment by andreeaipop** [comment]
I was using 06 May 2020 release of ADI Kuiper Linux with 0.19 libiio.
With a newer version and libiio version 0.21 the usb context is shown in the list of Available contexts.

**Comment by commodo** [comment]
thanks for the feedback 
will close
