### ISSUE TITLE
hats/eepromutils/ missing

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#36]
It would be convenient to have these pre-installed (since we are running on Pi's alot of the time).

https://github.com/raspberrypi/hats/tree/master/eepromutils

**Comment by rgetz** [comment]
There have been some recent updates on mainline that we should get (if possible).

**Comment by mirceacaprioru** [comment]
Added in https://github.com/analogdevicesinc/adi-kuiper-gen/pull/62
