### ISSUE TITLE
Pi BootROM version?

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#42]
I don't know if this is an "issue" or just good practice...

When running on a Pi, the first thing to do is update the [BootROM](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md)

```
root@analog:~# apt-get install rpi-eeprom-update
The following additional packages will be installed:
  flashrom libftdi1-2 libpci3 libusb-0.1-4 rpi-eeprom-images
The following NEW packages will be installed:
  flashrom libftdi1-2 libpci3 libusb-0.1-4 rpi-eeprom rpi-eeprom-images
0 upgraded, 6 newly installed, 0 to remove and 4 not upgraded.
Need to get 623 kB of archives.
After this operation, 8,141 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom-images all 4.0-1 [201 kB]
Get:2 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libpci3 armhf 1:3.5.2-1 [50.9 kB]       
Get:3 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom armhf 4.0-1 [205 kB]                      
Get:4 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libftdi1-2 armhf 1.4-1+b2 [27.7 kB]
Get:5 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libusb-0.1-4 armhf 2:0.1.12-32 [21.6 kB]
Get:6 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf flashrom armhf 1.0-1 [116 kB] 
Fetched 623 kB in 1s (455 kB/s)
root@analog:~# rpi-eeprom-update
BCM2711 detected
*** UPDATE REQUIRED ***
BOOTLOADER: update required
CURRENT: Fri 10 May 18:40:36 UTC 2019 (1557513636)
 LATEST: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
VL805: update required
CURRENT: 00013701
 LATEST: 000137ad
root@analog:~# rpi-eeprom-update -a
BCM2711 detected
*** INSTALLING EEPROM UPDATES ***
BOOTLOADER: update required
CURRENT: Fri 10 May 18:40:36 UTC 2019 (1557513636)
 LATEST: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
VL805: update required
CURRENT: 00013701
 LATEST: 000137ad
EEPROM updates pending. Please reboot to apply the update.
root@analog:~# reboot

root@analog:~# rpi-eeprom-update
BCM2711 detected
BOOTLOADER: up-to-date
CURRENT: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
 LATEST: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
VL805: up-to-date
CURRENT: 000137ad
 LATEST: 000137ad
```

Does this just go in "Running Kuiper on Pi" doc page?

**Comment by commodo** [comment]
This looks more on the RPi side than our side.
I'm not sure if we want this maintenance addition, since the RPi isn't a board we support directly, but more a board we deploy on.

If we add this on a Kuiper page, we're just asking for EZ questions in case people mess their things up.

And it just looks like boot code.
Once the system has booted up, we'd only care about the ADI parts, for which we definitely to do EZ work.

**Comment by rgetz** [comment]
agree - but USB OTG doesn't work properly without an update of the bootrom on the Pi4 side...

-Robin

**Comment by SRaus** [comment]
RPI4 doesn't use /boot/bootcode.bin but uses eeprom instead. File on eeprom can be updated using 'rpi-eeprom' package. By default rpi-eeprom-update service runs at startup and prompts for applying new updates if there are available, but this will overwrite also boot files (rpi kernels .img), /lib/modules and eeprom (affecting syncrona). This kind of update was turned of by [https://github.com/analogdevicesinc/adi-kuiper-gen/pull/85](https://github.com/analogdevicesinc/adi-kuiper-gen/pull/85 )
