### ISSUE TITLE
Verify compatibility with Raspberry Pi 400

### ISSUE THREAD

**Issue by mthoren-adi** [analogdevicesinc/adi-kuiper-gen#47]
An issue was posted to EngineerZone, indicating there may be an issue with the Raspberry Pi 400 keyboard:
https://ez.analog.com/linux-software-drivers/f/q-a/538041/adi-kuiper-on-raspberry-pi-400

If it's a straightforward fix/update, it would be great to support the 400.

**Comment by mirceacaprioru** [comment]
We will need to buy one of these to test first.

**Comment by mirceacaprioru** [comment]
We have shifted to kernel 5.4 so these has support for the RPI 400. The next build should work on this platform.
