### ISSUE TITLE
gr-iio not working, iio Python bindings, pyadi-iio, libm2k missing

### ISSUE THREAD

**Issue by mthoren-adi** [analogdevicesinc/adi-kuiper-gen#5]
Looks like gr-iio is still not installed properly. Rebuilding / installing with cmake -DCMAKE_INSTALL_PREFIX=/usr . fixes things (pluto FM receiver in examples runs fine.)

Would be good to have iio Python bindings installed by default, installer from libiio/bindings/python worked for both Python 2 and 3.

Same for pyadi-iio, perhaps installed from source (rather than pip), python 3 only.

Same for libm2k, with python 3 bindings.

Drivers checked so far: ADXL345, LTC2497, LTC4306, LM75 all working.

**Comment by tfcollins** [comment]
@mthoren-adi what was the issue you had with gr-iio?

and I probably need to do more releases for pyadi-iio :)

**Comment by mthoren-adi** [comment]
@tfcollins the pluto example (FM receiver) was failing when trying to import iio from gnuradio.
Re: more releases for pyadi-iio, hence the suggestion to install from source :) Either way would work, installing from pip, then installing from source, doesn't generate any weird messages. (I tried it.)

**Comment by mirceacaprioru** [comment]
Fixed gr-iio with https://github.com/analogdevicesinc/adi-kuiper-gen/pull/7

What would be the best way to add pyadi-iio and libm2k ? go with pip or from source ?

**Comment by tfcollins** [comment]
Pip is the easiest and we just pushed a new release yesterday so it should have the blocks Marks needs. If you want a "dev" update you can do a clone then `(sudo) python3 setup.py install`

**Comment by mirceacaprioru** [comment]
Treated in https://github.com/analogdevicesinc/adi-kuiper-gen/pull/12
