### ISSUE TITLE
avahi ssh service files missing

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adi-kuiper-gen#9]
In `/etc/avahi/services` there is currently an `iio.service` file (which shouldn't be there with an updated libiio - I will take care of in a different pull request).

but there should be an [ssh.service](https://github.com/lathiat/avahi/blob/master/avahi-daemon/ssh.service) file, so that you can look things up easier with the standard tools.

https://kodi.wiki/view/Avahi_Zeroconf for a few examples.

-Robin

**Comment by mirceacaprioru** [comment]
I can solve this with this command 
```
sudo cp /usr/share/doc/avahi-daemon/examples/ssh.service /etc/avahi/services/
```
Will add it to the build scripts

**Comment by rgetz** [comment]
Thanks - that will work - feel free to close when that's done.

**Comment by mirceacaprioru** [comment]
Added in https://github.com/analogdevicesinc/adi-kuiper-gen/pull/12
